language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "RF24:1.3.0,RF24Network:1.0.8,RF24Mesh:1.0.5"
  - tar x --directory=~/Arduino/libraries <(curl -SLs https://github.com/rocketscream/Low-Power/archive/V1.6.tar.gz)
  - ls ~/Arduino/libraries
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
